# Build environment image
FROM mcr.microsoft.com/dotnet/sdk:5.0 as build-env
WORKDIR /build
COPY . .

# Build & Publish
RUN dotnet publish webapi.csproj --no-cache -c Release -r linux-x64 --self-contained false -o /app

# Create container image from publish output
FROM mcr.microsoft.com/dotnet/aspnet:5.0 as runtime-env

WORKDIR /app
COPY --from=build-env /app .

ENTRYPOINT ["dotnet", "webapi.dll"]